version: 2.1

# コマンドーーーーーーーーーーーーーーーーーーーーーーーーーーー
commands:
  setup-node-and-puppeteer:
    steps:
      - checkout
      - run:
          name: npm install
          command: npm install
      - run:
          name: Install Puppeteer dependencies
          command: |
            sudo apt-get update
            sudo apt-get install -y \
              wget \
              ca-certificates \
              fonts-liberation \
              libappindicator3-1 \
              libasound2 \
              libatk-bridge2.0-0 \
              libatk1.0-0 \
              libcups2 \
              libdbus-1-3 \
              libdrm2 \
              libgbm1 \
              libnspr4 \
              libnss3 \
              libx11-xcb1 \
              libxcomposite1 \
              libxdamage1 \
              libxrandr2 \
              xdg-utils \
              --no-install-recommends
# コマンドーーーーーーーーーーーーーーーーーーーーーーーーーーー

# ジョブーーーーーーーーーーーーーーーーーーーーーーーーーーーー
jobs:
  auto-publish-notes:
    docker:
      - image: cimg/node:20.11
    steps:
      - setup-node-and-puppeteer
      - run:
          name: Run autoPublishNotes.js
          command: node autoPublishNotes.js

  auto-create-and-draft-note:
    docker:
      - image: cimg/node:20.11
    steps:
      - setup-node-and-puppeteer
      - run:
          name: Run autoCreateAndDraftNote.js
          command: node autoCreateAndDraftNote.js

  follow-from-articles:
    docker:
      - image: cimg/node:20.11
    steps:
      - setup-node-and-puppeteer
      - run:
          name: Run followFromArticles.js
          command: node follow/followFromArticles.js

  like-notes:
    docker:
      - image: cimg/node:20.11
    steps:
      - setup-node-and-puppeteer
      - run:
          name: Run likeUnlikedNotes.js
          command: node likeUnlikedNotes.js
# ジョブーーーーーーーーーーーーーーーーーーーーーーーーーーーー

# ワークフローーーーーーーーーーーーーーーーーーーーーーーーーー
workflows:
  version: 2
  scheduled-auto-publish:
    triggers:
      - schedule:
          cron: "45 2 * * *"   # JST 11:45
          filters:
            branches:
              only:
                - main
      - schedule:
          cron: "45 8 * * *"   # JST 17:45
          filters:
            branches:
              only:
                - main
      - schedule:
          cron: "45 14 * * *"  # JST 23:45
          filters:
            branches:
              only:
                - main
    jobs:
      - auto-publish-notes

  scheduled-auto-create-and-draft-note:
    triggers:
      - schedule:
          cron: "45 2 * * *"
          filters:
            branches:
              only:
                - main
      - schedule:
          cron: "45 8 * * *"
          filters:
            branches:
              only:
                - main
      - schedule:
          cron: "45 14 * * *"
          filters:
            branches:
              only:
                - main
    jobs:
      - auto-create-and-draft-note

  scheduled-follow-from-articles:
    triggers:
      - schedule:
          cron: "0 0,3,6,9,12,15,18,21 * * *" # JST 9:00,12:00,15:00,18:00,21:00,0:00,3:00,6:00
          filters:
            branches:
              only:
                - main
    jobs:
      - follow-from-articles

  scheduled-like-notes:
    triggers:
      - schedule:
          cron: "0 0,3,6,9,12,15,18,21 * * *" # JST 9:00,12:00,15:00,18:00,21:00,0:00,3:00,6:00
          filters:
            branches:
              only:
                - main
    jobs:
      - like-notes

  on-push:
    jobs:
      - auto-publish-notes:
          filters:
            branches:
              only:
                - main
      - auto-create-and-draft-note:
          filters:
            branches:
              only:
                - main
      - follow-from-articles:
          filters:
            branches:
              only:
                - main
      - like-notes:
          filters:
            branches:
              only:
                - main
# ワークフローーーーーーーーーーーーーーーーーーーーーーーーーー
