version: 2.1

jobs:
  # 共通ステップをYAMLアンカーで定義
  .common-steps: &common-steps
    steps:
      - checkout
      # 依存関係インストール
      - run:
          name: npm install
          command: npm install
      - run:
          name: Install Puppeteer dependencies
          command: |
            sudo apt-get update
            sudo apt-get install -y \
              wget \
              ca-certificates \
              fonts-liberation \
              libappindicator3-1 \
              libasound2 \
              libatk-bridge2.0-0 \
              libatk1.0-0 \
              libcups2 \
              libdbus-1-3 \
              libdrm2 \
              libgbm1 \
              libnspr4 \
              libnss3 \
              libx11-xcb1 \
              libxcomposite1 \
              libxdamage1 \
              libxrandr2 \
              xdg-utils \
              --no-install-recommends

  auto-publish-notes:
    docker:
      - image: cimg/node:20.11
    <<: *common-steps
    steps:
      - run:
          name: Run autoPublishNotes.js
          command: node autoPublishNotes.js

  auto-create-and-draft-note:
    docker:
      - image: cimg/node:20.11
    <<: *common-steps
    steps:
      - run:
          name: Run autoCreateAndDraftNote.js
          command: node autoCreateAndDraftNote.js

workflows:
  version: 2
  scheduled-auto-publish:
    triggers:
      - schedule:
          cron: "45 2 * * *"   # JST 11:45
          filters:
            branches:
              only:
                - main
      - schedule:
          cron: "45 8 * * *"   # JST 17:45
          filters:
            branches:
              only:
                - main
      - schedule:
          cron: "45 14 * * *"  # JST 23:45
          filters:
            branches:
              only:
                - main
    jobs:
      - auto-publish-notes

  scheduled-auto-create-and-draft-note:
    triggers:
      - schedule:
          cron: "45 2 * * *"
          filters:
            branches:
              only:
                - main
      - schedule:
          cron: "45 8 * * *"
          filters:
            branches:
              only:
                - main
      - schedule:
          cron: "45 14 * * *"
          filters:
            branches:
              only:
                - main
    jobs:
      - auto-create-and-draft-note

  on-push:
    jobs:
      - auto-publish-notes:
          filters:
            branches:
              only:
                - main
      - auto-create-and-draft-note:
          filters:
            branches:
              only:
                - main
