version: 2.1

jobs:
  auto-publish-notes:
    docker:
      - image: cimg/node:20.11 # Node.js 20系の公式イメージ
    steps:
      - checkout
      # 依存関係インストール
      - run:
          name: npm install
          command: npm install
      - run:
          name: Install Puppeteer dependencies
          command: |
            sudo apt-get update
            sudo apt-get install -y \
              wget \
              ca-certificates \
              fonts-liberation \
              libappindicator3-1 \
              libasound2 \
              libatk-bridge2.0-0 \
              libatk1.0-0 \
              libcups2 \
              libdbus-1-3 \
              libdrm2 \
              libgbm1 \
              libnspr4 \
              libnss3 \
              libx11-xcb1 \
              libxcomposite1 \
              libxdamage1 \
              libxrandr2 \
              xdg-utils \
              --no-install-recommends
      # スクリプト実行
      - run:
          name: Run autoPublishNotes.js
          command: node autoPublishNotes.js
    environment:
      NOTE_EMAIL: $NOTE_EMAIL
      NOTE_PASSWORD: $NOTE_PASSWORD

workflows:
  version: 2
  scheduled-auto-publish:
    triggers:
      - schedule:
          cron: "45 2 * * *"   # JST 11:45
          filters:
            branches:
              only:
                - main
      - schedule:
          cron: "45 8 * * *"   # JST 17:45
          filters:
            branches:
              only:
                - main
      - schedule:
          cron: "45 14 * * *"  # JST 23:45
          filters:
            branches:
              only:
                - main
    jobs:
      - auto-publish-notes

  on-push:
    jobs:
      - auto-publish-notes:
          filters:
            branches:
              only:
                - main
