version: 2.1

# コマンドーーーーーーーーーーーーーーーーーーーーーーーーーーー
commands:
  setup-node-and-puppeteer:
    steps:
      - checkout
      - run:
          name: npm install
          command: npm install
      - run:
          name: Install Puppeteer dependencies
          command: |
            sudo apt-get update
            sudo apt-get install -y \
              wget \
              ca-certificates \
              fonts-liberation \
              libappindicator3-1 \
              libasound2 \
              libatk-bridge2.0-0 \
              libatk1.0-0 \
              libcups2 \
              libdbus-1-3 \
              libdrm2 \
              libgbm1 \
              libnspr4 \
              libnss3 \
              libx11-xcb1 \
              libxcomposite1 \
              libxdamage1 \
              libxrandr2 \
              xdg-utils \
              --no-install-recommends
# コマンドーーーーーーーーーーーーーーーーーーーーーーーーーーー

# ジョブーーーーーーーーーーーーーーーーーーーーーーーーーーーー
jobs:
  run-js-script:
    parameters:
      script-file:
        type: string
    docker:
      - image: cimg/node:20.11
    steps:
      - setup-node-and-puppeteer
      - run:
          name: Run << parameters.script-file >>
          command: node << parameters.script-file >>

  # auto-publish-notes:
  #   docker:
  #     - image: cimg/node:20.11
  #   steps:
  #     - setup-node-and-puppeteer
  #     - run:
  #         name: Run autoPublishNotes.js
  #         command: node autoPublishNotes.js

  # auto-create-and-draft-note:
  #   docker:
  #     - image: cimg/node:20.11
  #   steps:
  #     - setup-node-and-puppeteer
  #     - run:
  #         name: Run autoCreateAndDraftNote.js
  #         command: node autoCreateAndDraftNote.js

  # follow-from-articles:
  #   docker:
  #     - image: cimg/node:20.11
  #   steps:
  #     - setup-node-and-puppeteer
  #     - run:
  #         name: Run followFromArticles.js
  #         command: node follow/followFromArticles.js

  # like-notes:
  #   docker:
  #     - image: cimg/node:20.11
  #   steps:
  #     - setup-node-and-puppeteer
  #     - run:
  #         name: Run likeUnlikedNotes.js
  #         command: node likeUnlikedNotes.js
# ジョブーーーーーーーーーーーーーーーーーーーーーーーーーーーー

# ワークフローーーーーーーーーーーーーーーーーーーーーーーーーー
workflows:
  version: 2
  scheduled-all:
    triggers:
      - schedule:
          cron: "45 2 * * *"
          filters:
            branches:
              only:
                - main
      - schedule:
          cron: "45 8 * * *"
          filters:
            branches:
              only:
                - main
      - schedule:
          cron: "45 14 * * *"
          filters:
            branches:
              only:
                - main
      - schedule:
          cron: "0 0,3,6,9,12,15,18,21 * * *"
          filters:
            branches:
              only:
                - main
    jobs:
      - run-js-script:
          name: auto-publish-notes
          script-file: autoPublishNotes.js
      - run-js-script:
          name: auto-create-and-draft-note
          script-file: autoCreateAndDraftNote.js
      - run-js-script:
          name: follow-from-articles
          script-file: follow/followFromArticles.js
      - run-js-script:
          name: like-notes
          script-file: likeUnlikedNotes.js

  on-push:
    jobs:
      - run-js-script:
          name: auto-publish-notes
          script-file: autoPublishNotes.js
          filters:
            branches:
              only:
                - main
      - run-js-script:
          name: auto-create-and-draft-note
          script-file: autoCreateAndDraftNote.js
          filters:
            branches:
              only:
                - main
      - run-js-script:
          name: follow-from-articles
          script-file: follow/followFromArticles.js
          filters:
            branches:
              only:
                - main
      - run-js-script:
          name: like-notes
          script-file: likeUnlikedNotes.js
          filters:
            branches:
              only:
                - main
# ワークフローーーーーーーーーーーーーーーーーーーーーーーーーー
